### ISSUE TITLE
add a filder field to the block stats site

### ISSUE THREAD

**Issue by Teekeks** [Zweistein2/minestats#1]
With the rate of new blocks being added, it gets harder and harder to find the block you want to look at.
A simple filter would fix that.

**Comment by Zweistein2** [comment]
What should the filter look like?

Should it filter by categories? If so, what categories do you have in mind? 
"building blocks", "deco blocks", "usable blocks", ...?
or more like "soil blocks", "stone blocks", "ore blocks", ...?

If not... how should the filter work then?

**Comment by Teekeks** [comment]
I was thinking about a text input, so a filter by name / tag

**Comment by Zweistein2** [comment]
Implemented by commit #d11a3d88c4da2335cd77fbd8abb6911c5f46fb4b
